"""Seed de destination_places — curación de Bogotá del Companion.

Cada lugar: zona (barrio/área — también es la etiqueta humana que devuelve el
reverse-geocode), categoría, coordenadas PROPIAS del lugar, una descripción ya
redactada para el motor (dice POR QUÉ se recomienda y, cuando aplica, su fuente),
nivel de confianza y, para landmarks/lugares de nombre único, `maps_query`
(nombre buscable → Google Maps lleva al pin oficial, "Cómo llegar" más preciso
que una coordenada aproximada).

Campo `dir`: dirección real del lugar. NO se guarda en la BD (db lo ignora);
sirve para (1) que el Companion pueda decir la dirección y (2) regenerar
`geocode_seed.py` y verificar coordenadas con Nominatim. Las coordenadas aquí
son aproximaciones a nivel calle/carrera (la cuadrícula de Bogotá es regular:
calles suben al norte, carreras al occidente) — suficientes para rankear por
distancia. Para precisión fina, correr `geocode_seed.py` una vez.

FUENTES (jun. 2026): Latin America's 50 Best Restaurants 2025 (ceremonia 2 dic
2025, Antigua) y su lista extendida 51–100; The World's 100 Best Coffee Shops
2026; Guía Michelin Colombia 2025 (NOTA: en Colombia Michelin solo otorga
"Llaves" a HOTELES — NO hay estrellas de restaurantes en el país, no se
afirman); Revista Diners, Revista Exclama, guías locales (Lure, DistritoCH) y
señales sociales reportadas. Lo "viral de la semana" NO va aquí — eso lo
aporta el Destination Scanner en vivo; este seed es lo atemporal y verificable.

Categorías (texto libre que lee el scoring): restaurante, cafe, bar, parque,
atraccion, mercado, mirador, compras, experiencia, excursion.

Idempotente: db.seed_destination_places() inserta una sola vez. Ampliar = agregar
diccionarios aquí (y re-sembrar: rm voyra.db).
"""
from . import geo

BOGOTA = [
    # ════════════ ALTA COCINA — rankings internacionales ════════════
    {
        "city_display": "Bogotá", "name": "El Chato", "category": "restaurante", "zona": "Chapinero Alto",
        "dir": "Calle 65 #4-76, Chapinero, Bogotá, Colombia",
        "maps_query": "El Chato restaurante Bogotá",
        "lat": 4.6402, "lng": -74.0625,
        "descripcion": "El #1 de Latin America's 50 Best Restaurants 2025 — nombrado el Mejor Restaurante de Latinoamérica. Del chef Álvaro Clavijo: alta cocina colombiana de temporada que realza el producto local con técnica global. Reservar con semanas de anticipación.",
        "confianza": "muy_alta",
    },
    {
        "city_display": "Bogotá", "name": "Leo Cocina y Cava", "category": "restaurante", "zona": "Chapinero / Centro Internacional",
        "dir": "Calle 27B #6-75, Bogotá, Colombia",
        "maps_query": "Leo Cocina y Cava Bogotá",
        "lat": 4.6126, "lng": -74.0686,
        "descripcion": "De la chef Leonor Espinosa, #23 en Latin America's 50 Best 2025 y Basque Culinary World Prize. Su menú 'Ciclo-Bioma' recorre la biodiversidad colombiana en 20+ momentos; coctelería de su hija sommelier Laura Hernández. Una de las experiencias cumbre de la ciudad.",
        "confianza": "muy_alta",
    },
    {
        "city_display": "Bogotá", "name": "Afluente", "category": "restaurante", "zona": "Chapinero",
        "dir": "Bogotá, Colombia",
        "maps_query": "Afluente restaurante Bogotá",
        "lat": 4.6440, "lng": -74.0628,
        "descripcion": "Debutó en el puesto #34 de Latin America's 50 Best 2025 — uno de los grandes estrenos colombianos del año. Cocina de autor que lee los ríos y ecosistemas del país. Reservar con anticipación.",
        "confianza": "muy_alta",
    },
    {
        "city_display": "Bogotá", "name": "Humo Negro", "category": "restaurante", "zona": "Chapinero Alto",
        "dir": "Carrera 5 #56-06, Chapinero, Bogotá, Colombia",
        "maps_query": "Humo Negro Carrera 5 56-06 Chapinero Bogotá",
        "lat": 4.6404, "lng": -74.0608,
        "descripcion": "#41 en Latin America's 50 Best 2025. Del chef Jaime Torregrosa (ex-El Chato): izakaya que cruza Japón, Latinoamérica y lo nórdico con producto colombiano sostenible (pirarucú amazónico). Carrera 5 #56-06.",
        "confianza": "muy_alta",
    },
    {
        "city_display": "Bogotá", "name": "Oda", "category": "restaurante", "zona": "Zona G",
        "dir": "Carrera 6 #66-46, Bogotá, Colombia",
        "maps_query": "Oda Restaurante Bogotá Chapinero",
        "lat": 4.6575, "lng": -74.0588,
        "descripcion": "#76 en la lista extendida de Latin America's 50 Best 2025 y ganador del Sustainable Restaurant Award. Dentro del G Lounge (Zona G): menú contemporáneo de ingredientes autóctonos con foco en sostenibilidad.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Criterión", "category": "restaurante", "zona": "La Candelaria / Centro",
        "dir": "Calle 69A #5-75, Bogotá, Colombia",
        "maps_query": "Criterion restaurante Rausch Bogotá",
        "lat": 4.6520, "lng": -74.0598,
        "descripcion": "El buque insignia de los hermanos Rausch, referente de alta cocina franco-colombiana en Bogotá desde hace dos décadas. Elegante, ideal para una cena especial o de negocios. (No hay estrellas Michelin en Colombia; es reconocimiento local e internacional de crítica.)",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "El Cielo Bogotá", "category": "restaurante", "zona": "Zona G / Chapinero",
        "dir": "Calle 70 #4-47, Zona G, Chapinero, Bogotá, Colombia",
        "maps_query": "Elcielo Restaurant Bogotá Calle 70 4-47 Zona G",
        "lat": 4.6477, "lng": -74.0588,
        "descripcion": "Experiencia multisensorial del chef Juan Manuel Barrientos (estrella Michelin con El Cielo en EE. UU.). Menú-degustación con 'momentos' que van más allá del plato, en Zona G. Reservar; ideal para ocasiones.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Mesa Franca", "category": "restaurante", "zona": "Chapinero Alto",
        "dir": "Calle 61 #5-56, Chapinero, Bogotá, Colombia",
        "maps_query": "Mesa Franca Calle 61 5-56 Chapinero Bogotá",
        "lat": 4.6480, "lng": -74.0612,
        "descripcion": "Casa de Chapinero muy querida por la crítica local: cocina de autor de raíz criolla y coctelería con viche del Pacífico (la 'Mula Pacífica'). Ambiente relajado, platos para compartir. Calle 61 #5-56.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Salvo Patria", "category": "restaurante", "zona": "Chapinero Alto",
        "dir": "Carrera 4 Bis #58-60, Chapinero Alto, Bogotá, Colombia",
        "maps_query": "Salvo Patria Carrera 4 Bis 58-60 Chapinero Bogotá",
        "lat": 4.6395, "lng": -74.0618,
        "descripcion": "Más de 15 años de cocina colombiana de temporada en casa de Chapinero Alto, un clásico moderno de la ciudad. Buen café de día, cocina de producto de noche; platos como los agnolotti de mazorca.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Prudencia", "category": "restaurante", "zona": "La Candelaria",
        "dir": "Carrera 2 #11-34, La Candelaria, Bogotá, Colombia",
        "maps_query": "Prudencia restaurante La Candelaria Bogotá",
        "lat": 4.5972, "lng": -74.0712,
        "descripcion": "Joya escondida en un patio colonial de La Candelaria: menú del día corto y cambiante, cocina de horno y producto de mercado. Solo almuerzos entre semana, con reserva — perfecto tras los museos del centro.",
        "confianza": "media_alta",
    },
    {
        "city_display": "Bogotá", "name": "Mini-Mal", "category": "restaurante", "zona": "Chapinero",
        "dir": "Transversal 4 Bis #57-52, Chapinero, Bogotá, Colombia",
        "maps_query": "Mini-Mal restaurante Bogotá",
        "lat": 4.6398, "lng": -74.0635,
        "descripcion": "Cocina que celebra la biodiversidad colombiana y los ingredientes de las regiones (Amazonía, Pacífico, Caribe). Propuesta original y sin pretensiones — una buena entrada a los sabores del país.",
        "confianza": "media_alta",
    },
    {
        "city_display": "Bogotá", "name": "Harry Sasson", "category": "restaurante", "zona": "Zona G",
        "dir": "Carrera 9 #75-70, Bogotá, Colombia",
        "maps_query": "Harry Sasson restaurante Bogotá",
        "lat": 4.6612, "lng": -74.0581,
        "descripcion": "Clásico mayor de la gastronomía bogotana, en una casa espectacular: fusión de técnica europea y producto colombiano, gran servicio. Ideal para una cena elegante o de negocios.",
        "confianza": "alta",
    },

    # ════════════ RESTAURANTES — carne, mar, temáticos ════════════
    {
        "city_display": "Bogotá", "name": "La Cabrera", "category": "restaurante", "zona": "Zona G",
        "dir": "Calle 69A #5-19, Zona G, Bogotá, Colombia",
        "maps_query": "La Cabrera Parrilla Argentina Calle 69A 5-19 Zona G Bogotá",
        "lat": 4.6562, "lng": -74.0566,
        "descripcion": "Parrilla de referencia para cortes de carne al estilo argentino-colombiano. Varias sedes; la de Zona G es la más concurrida. Buen punto para una comida contundente.",
        "confianza": "media_alta",
    },
    {
        "city_display": "Bogotá", "name": "Club Colombia", "category": "restaurante", "zona": "Zona G",
        "dir": "Calle 82 #9-11, Bogotá, Colombia",
        "maps_query": "Restaurante Club Colombia Bogotá",
        "lat": 4.6668, "lng": -74.0552,
        "descripcion": "Alta cocina colombiana tradicional (grupo Crepes & Waffles) en casa elegante: ajiaco, posta, postres criollos. La forma más cómoda de probar lo clásico del país bien ejecutado.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Central Cevichería", "category": "restaurante", "zona": "Zona T / El Nogal",
        "dir": "Carrera 13 #85-14, Zona Rosa, Bogotá, Colombia",
        "maps_query": "Central Cevicheria Carrera 13 85-14 Zona Rosa Bogotá",
        "lat": 4.6672, "lng": -74.0535,
        "descripcion": "Cevichería animada y muy popular cerca de la Zona T — ceviches, cocteles y ambiente de tarde-noche. Buena opción informal antes de salir.",
        "confianza": "media",
    },
    {
        "city_display": "Bogotá", "name": "Pizzardi Artigianale", "category": "restaurante", "zona": "Zona G",
        "dir": "Calle 81 #11-17, Bogotá, Colombia",
        "maps_query": "Pizzardi Artigianale Calle 81 11-17 Bogotá",
        "lat": 4.6588, "lng": -74.0588,
        "descripcion": "Pizza napolitana con certificación de la True Neapolitan Pizza Association, considerada de las mejores de Colombia. Masa fermentada, horno de leña.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "La Lucha Sanguchería", "category": "restaurante", "zona": "Zona G",
        "dir": "Avenida Calle 85 #12-95, Bogotá, Colombia",
        "maps_query": "La Lucha Sangucheria Calle 85 12-95 Bogotá",
        "lat": 4.6560, "lng": -74.0596,
        "descripcion": "Sandwichería peruana informal y rápida — clásico para un almuerzo bueno y económico en Zona G. Varias sedes en la ciudad.",
        "confianza": "media",
    },

    # ════════════ TRADICIONAL E ICÓNICO ════════════
    {
        "city_display": "Bogotá", "name": "La Puerta Falsa", "category": "restaurante", "zona": "La Candelaria",
        "dir": "Calle 11 #6-50, La Candelaria, Bogotá, Colombia",
        "maps_query": "La Puerta Falsa Bogotá",
        "lat": 4.5980, "lng": -74.0745,
        "descripcion": "Centenaria, a pasos de la Plaza de Bolívar — la parada obligada de tamal santafereño y chocolate con almojábana en el centro histórico. Pequeñísima y siempre llena; vale la fila.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Restaurante La Puerta de la Tradición (Santa Fe)", "category": "restaurante", "zona": "La Candelaria",
        "dir": "Calle 11 #5-11, La Candelaria, Bogotá, Colombia",
        "maps_query": "La Puerta de la Tradicion restaurante Calle 11 5-11 La Candelaria Bogotá",
        "lat": 4.5969, "lng": -74.0740,
        "descripcion": "Cocina santafereña tradicional en el centro histórico: ajiaco con pollo, mazorca y alcaparras, puchero. Buen plan de almuerzo entre museos.",
        "confianza": "media",
    },
    {
        "city_display": "Bogotá", "name": "Casa Vieja", "category": "restaurante", "zona": "Centro Internacional",
        "dir": "Avenida Jiménez #3-63, Bogotá, Colombia",
        "maps_query": "Restaurante Casa Vieja Bogotá",
        "lat": 4.6018, "lng": -74.0698,
        "descripcion": "Institución de la cocina colombiana tradicional desde 1965: su ajiaco santafereño es de los más reconocidos de la ciudad. Ambiente clásico, ideal para un almuerzo típico.",
        "confianza": "media_alta",
    },
    {
        "city_display": "Bogotá", "name": "Crepes & Waffles", "category": "restaurante", "zona": "Varias sedes",
        "dir": "Calle 85 #11-69, Bogotá, Colombia",
        "maps_query": "Crepes & Waffles Bogotá",
        "lat": 4.6680, "lng": -74.0548,
        "descripcion": "La cadena más querida de Colombia: crepes dulces y salados, ensaladas y helados a muy buen precio, calidad consistente y empleo mayormente a mujeres cabeza de hogar. Apuesta segura en cualquier zona — nunca te van a 'tumbar'.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Andrés Carne de Res (Chía)", "category": "restaurante", "zona": "Chía (afueras)",
        "dir": "Calle 3 #11A-56, Chía, Cundinamarca, Colombia",
        "maps_query": "Andrés Carne de Res Chía",
        "lat": 4.8617, "lng": -74.0533,
        "descripcion": "El templo original de la rumba y la carne en Chía, a ~40 min al norte: un universo de decoración, show, baile y comida que hay que vivir una vez. Mejor viernes/sábado en la noche, ir en taxi o app (queda fuera de Bogotá). Su versión urbana es Andrés D.C. en la Zona T.",
        "confianza": "muy_alta",
    },

    # ════════════ CAFÉ DE ESPECIALIDAD Y PANADERÍAS ════════════
    {
        "city_display": "Bogotá", "name": "Tropicalia Coffee", "category": "cafe", "zona": "Chapinero Alto",
        "dir": "Calle 81A #8-23, Bogotá, Colombia",
        "lat": 4.6660, "lng": -74.0558,
        "descripcion": "#9 mundial en The World's 100 Best Coffee Shops 2026 — la cafetería colombiana mejor posicionada del planeta. Métodos V60, Chemex, Aeropress; brunch y catas guiadas. Calle 81A #8-23.",
        "confianza": "muy_alta",
    },
    {
        "city_display": "Bogotá", "name": "Azahar Café", "category": "cafe", "zona": "Quinta Camacho",
        "dir": "Calle 69A #10-44, Bogotá, Colombia",
        "maps_query": "Azahar Café Quinta Camacho Bogotá",
        "lat": 4.6535, "lng": -74.0608,
        "descripcion": "Café de especialidad colombiano consolidado, con tostión propia y trazabilidad de origen. La sede de Quinta Camacho, en casa antigua, es de las más bonitas para sentarse a trabajar o desayunar.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Café Cultor", "category": "cafe", "zona": "Chapinero",
        "dir": "Calle 70A #9-44, Quinta Camacho, Bogotá, Colombia",
        "maps_query": "Café Cultor Casa Calle 70A 9-44 Quinta Camacho Bogotá",
        "lat": 4.6520, "lng": -74.0588,
        "descripcion": "Tostador de especialidad con causa social y cafés de origen colombiano bien presentados. Buen lugar para probar un filtrado distinto cada visita.",
        "confianza": "media_alta",
    },
    {
        "city_display": "Bogotá", "name": "Catación Pública", "category": "cafe", "zona": "Quinta Camacho",
        "dir": "Carrera 6 #66-46, Bogotá, Colombia",
        "maps_query": "Catación Pública Bogotá",
        "lat": 4.6555, "lng": -74.0598,
        "descripcion": "Más que un café: hacen catas y talleres para entender el café colombiano de origen. Ideal si quieres aprender a catar, no solo tomar. Reservar la experiencia.",
        "confianza": "media_alta",
    },
    {
        "city_display": "Bogotá", "name": "Libertario Coffee Roasters", "category": "cafe", "zona": "Chapinero",
        "dir": "Calle 70A #5-37, Zona G, Bogotá, Colombia",
        "maps_query": "Libertario Coffee Roasters Calle 70A 5-37 Zona G Bogotá",
        "lat": 4.6418, "lng": -74.0610,
        "descripcion": "Tostador de especialidad con varias barras en la ciudad, fuerte en espresso y métodos. Buena parada de café serio en Chapinero.",
        "confianza": "media",
    },
    {
        "city_display": "Bogotá", "name": "Amor Perfecto", "category": "cafe", "zona": "Usaquén",
        "dir": "Carrera 6 #117-50, Usaquén, Bogotá, Colombia",
        "maps_query": "Amor Perfecto café Carrera 6 117-50 Usaquén Bogotá",
        "lat": 4.6940, "lng": -74.0325,
        "descripcion": "Pionera colombiana del café de especialidad — acercó los cafés premium de origen único al consumidor local. Buena parada cerca del mercado de Usaquén.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Colo Coffee", "category": "cafe", "zona": "Parque de la 93 (Chicó)",
        "dir": "Carrera 13 #83-19, Bogotá, Colombia",
        "maps_query": "Colo Coffee Carrera 13 83-19 Bogotá Colombia",
        "lat": 4.6757, "lng": -74.0478,
        "descripcion": "Cafetería de especialidad amplia y con buen WiFi cerca de la Calle 93 — citada en rutas de café de Bogotá como buen sitio para trabajar o pasar la tarde.",
        "confianza": "media_alta",
    },
    {
        "city_display": "Bogotá", "name": "Brot Bakery & Café", "category": "cafe", "zona": "Zona T / El Nogal",
        "dir": "Calle 81 #7-93, Bogotá, Colombia",
        "maps_query": "Brot Bakery Cafe Calle 81 7-93 Bogotá",
        "lat": 4.6648, "lng": -74.0555,
        "descripcion": "Panadería-café clásica desde 1999, famosa por su baguette de chocolate y sus desayunos. Recurrente en los tops de brunch de la ciudad; terraza agradable. Calle 81 #7-93.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Masa (Rosales)", "category": "cafe", "zona": "Rosales / Zona G",
        "dir": "Calle 70A #4-83, Bogotá, Colombia",
        "maps_query": "Masa Rosales Calle 70A 4-83 Bogotá",
        "lat": 4.6541, "lng": -74.0563,
        "descripcion": "Panadería y brunch de referencia: croissant de almendras, pan recién horneado, pan de canela. De los mejores desayunos de Bogotá; suele llenarse el fin de semana. Calle 70A #4-83.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Árbol del Pan", "category": "cafe", "zona": "Chapinero Alto",
        "dir": "Carrera 4 #66-46, Chapinero, Bogotá, Colombia",
        "maps_query": "Árbol del Pan panadería Chapinero Bogotá",
        "lat": 4.6512, "lng": -74.0570,
        "descripcion": "Panadería artesanal encantadora y destino de brunch muy querido en Chapinero — de las panaderías mejor valoradas de la ciudad. Cra 4 #66-46.",
        "confianza": "media_alta",
    },

    # ════════════ BARES Y VIDA NOCTURNA ════════════
    {
        "city_display": "Bogotá", "name": "Andrés D.C.", "category": "bar", "zona": "Zona T / Zona Rosa",
        "dir": "Calle 82 #12-21, Bogotá, Colombia",
        "maps_query": "Andrés DC Calle 82 Zona T Bogotá",
        "lat": 4.6680, "lng": -74.0533,
        "descripcion": "La sede urbana del mítico Andrés Carne de Res, en plena Zona Rosa: cuatro pisos de restaurante, bar y baile. Uno de los planes nocturnos más emblemáticos y seguros para empezar la noche en Bogotá.",
        "confianza": "muy_alta",
    },
    {
        "city_display": "Bogotá", "name": "Gaira Café Cumbia House", "category": "bar", "zona": "Chicó / Calle 96",
        "dir": "Carrera 13 #96-11, Bogotá, Colombia",
        "maps_query": "Gaira Café Cumbia House Bogotá",
        "lat": 4.6840, "lng": -74.0480,
        "descripcion": "El bar-restaurante de la familia Vives: música en vivo, vallenato y cumbia, comida del Caribe colombiano. Plan de noche muy colombiano y festivo; mejor reservar fin de semana.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Theatron", "category": "bar", "zona": "Chapinero",
        "dir": "Calle 58 #10-32, Chapinero, Bogotá, Colombia",
        "maps_query": "Theatron de Película Bogotá",
        "lat": 4.6395, "lng": -74.0648,
        "descripcion": "La discoteca LGBTIQ+ más grande de Latinoamérica: múltiples salas, cada una con su género musical, en un antiguo teatro de Chapinero. Ícono de la noche bogotana. Entrada con barra incluida; ir en grupo y en taxi/app.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Armando Records", "category": "bar", "zona": "Zona T",
        "dir": "Calle 85 #14-46, Bogotá, Colombia",
        "maps_query": "Armando Records Bogotá",
        "lat": 4.6688, "lng": -74.0548,
        "descripcion": "Bar y terraza icónica de la Calle 85: música alternativa e indie, rooftop con ambiente. Punto de referencia de la rumba joven en la Zona T.",
        "confianza": "media_alta",
    },
    {
        "city_display": "Bogotá", "name": "Baum", "category": "bar", "zona": "Centro / Las Nieves",
        "dir": "Calle 33 #6-24, Bogotá, Colombia",
        "maps_query": "Baum club Bogotá",
        "lat": 4.6210, "lng": -74.0678,
        "descripcion": "El club de música electrónica de referencia en Bogotá (techno y house), con line-ups internacionales. Para quien busca rumba electrónica de verdad. Abre tarde; ir en app.",
        "confianza": "media_alta",
    },
    {
        "city_display": "Bogotá", "name": "Video Club", "category": "bar", "zona": "Chapinero",
        "dir": "Calle 64 #13-09, Chapinero, Bogotá, Colombia",
        "maps_query": "Video Club bar Calle 64 13-09 Chapinero Bogotá",
        "lat": 4.6560, "lng": -74.0560,
        "descripcion": "Club de electrónica querido por la escena local, ambiente alternativo y buenos DJs. Plan de noche para bailar sin pretensiones.",
        "confianza": "media",
    },
    {
        "city_display": "Bogotá", "name": "Apache Rooftop (Click Clack)", "category": "bar", "zona": "Zona G",
        "dir": "Carrera 11 #93-77, Bogotá, Colombia",
        "maps_query": "Apache Rooftop Click Clack Hotel Bogotá",
        "lat": 4.6760, "lng": -74.0488,
        "descripcion": "Bar en la azotea del hotel Click Clack con vista de la ciudad y los cerros — cocteles al atardecer. Plan más relajado y fotogénico que la discoteca. Cerca del Parque de la 93.",
        "confianza": "media_alta",
    },
    {
        "city_display": "Bogotá", "name": "Galería Café Libro", "category": "bar", "zona": "Zona T / Centro",
        "dir": "Carrera 11A #93-42, Parque de la 93, Bogotá, Colombia",
        "maps_query": "Galería Café Libro Carrera 11A 93-42 Parque 93 Bogotá",
        "lat": 4.6662, "lng": -74.0540,
        "descripcion": "Templo de la salsa en Bogotá: pista, orquesta y baile hasta tarde. Si quieres salsa de verdad, este es el sitio. Hay sede en la Zona T y en el centro.",
        "confianza": "media_alta",
    },
    {
        "city_display": "Bogotá", "name": "Bogotá Beer Company (BBC)", "category": "bar", "zona": "Varias sedes",
        "dir": "Carrera 12 #83-33, Bogotá, Colombia",
        "maps_query": "Bogotá Beer Company Zona T",
        "lat": 4.6678, "lng": -74.0538,
        "descripcion": "La cervecería artesanal más conocida de la ciudad, con sedes por toda Bogotá. Plan informal y seguro para unas cervezas; buena parada antes de salir de rumba.",
        "confianza": "media_alta",
    },
    {
        "city_display": "Bogotá", "name": "Taninos Park Wines", "category": "bar", "zona": "Parkway / La Soledad",
        "dir": "Calle 39 #21-19, La Soledad, Bogotá, Colombia",
        "maps_query": "Taninos Park Wines Calle 39 21-19 Parkway Bogotá",
        "lat": 4.6285, "lng": -74.0725,
        "descripcion": "Bar de vinos en el Parkway con más de 140 etiquetas del mundo — plan tranquilo de copas en una zona bohemia y caminable. Buen panorama de noche relajada.",
        "confianza": "media",
    },

    # ════════════ MUSEOS Y CULTURA ════════════
    {
        "city_display": "Bogotá", "name": "Museo del Oro", "category": "atraccion", "zona": "La Candelaria / Centro",
        "dir": "Carrera 6 #15-88, Bogotá, Colombia",
        "maps_query": "Museo del Oro Bogotá",
        "lat": 4.6019, "lng": -74.0721,
        "descripcion": "Una de las colecciones de orfebrería prehispánica más importantes del mundo. Imprescindible; entrada económica y gratis los domingos. Dedícale 1.5–2 horas.",
        "confianza": "muy_alta",
    },
    {
        "city_display": "Bogotá", "name": "Museo Botero", "category": "atraccion", "zona": "La Candelaria",
        "dir": "Calle 11 #4-41, La Candelaria, Bogotá, Colombia",
        "maps_query": "Museo Botero Bogotá",
        "lat": 4.5973, "lng": -74.0726,
        "descripcion": "Colección donada por Fernando Botero en casa colonial: obras suyas más Picasso, Dalí, Monet y Renoir. Entrada GRATUITA. A 10 min a pie del Museo del Oro.",
        "confianza": "muy_alta",
    },
    {
        "city_display": "Bogotá", "name": "Museo Nacional de Colombia", "category": "atraccion", "zona": "Centro Internacional",
        "dir": "Carrera 7 #28-66, Bogotá, Colombia",
        "maps_query": "Museo Nacional de Colombia",
        "lat": 4.6155, "lng": -74.0686,
        "descripcion": "El museo más antiguo del país, en un edificio que fue penitenciaría (El Panóptico): historia, arqueología y arte colombiano. Buen plan de medio día; gratis los domingos.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "MAMBO — Museo de Arte Moderno", "category": "atraccion", "zona": "Centro Internacional",
        "dir": "Calle 24 #6-00, Bogotá, Colombia",
        "maps_query": "Museo de Arte Moderno de Bogotá MAMBO",
        "lat": 4.6122, "lng": -74.0690,
        "descripcion": "Arte moderno y contemporáneo latinoamericano en un edificio de Rogelio Salmona. Exposiciones rotativas; buena parada cultural en el Centro Internacional.",
        "confianza": "media_alta",
    },
    {
        "city_display": "Bogotá", "name": "Quinta de Bolívar", "category": "atraccion", "zona": "La Candelaria / Cerros",
        "dir": "Calle 20 #2-91 Este, Bogotá, Colombia",
        "maps_query": "Casa Museo Quinta de Bolívar Bogotá",
        "lat": 4.6029, "lng": -74.0668,
        "descripcion": "Casa-museo donde vivió Simón Bolívar, con jardines a los pies de Monserrate. Tranquila y bonita; combínala con la subida a Monserrate.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Biblioteca Luis Ángel Arango", "category": "atraccion", "zona": "La Candelaria",
        "dir": "Calle 11 #4-14, La Candelaria, Bogotá, Colombia",
        "maps_query": "Biblioteca Luis Ángel Arango Bogotá",
        "lat": 4.5969, "lng": -74.0731,
        "descripcion": "Una de las bibliotecas más importantes de Latinoamérica, con salas de exposición y conciertos. Arquitectura notable; entrada libre a buena parte de sus espacios.",
        "confianza": "media_alta",
    },
    {
        "city_display": "Bogotá", "name": "Teatro Colón", "category": "atraccion", "zona": "La Candelaria",
        "dir": "Calle 10 #5-32, La Candelaria, Bogotá, Colombia",
        "maps_query": "Teatro Colón Bogotá",
        "lat": 4.5966, "lng": -74.0739,
        "descripcion": "El teatro nacional, joya del siglo XIX restaurada con techos pintados a mano. Vale la pena un tour guiado o una función. En pleno centro histórico.",
        "confianza": "media_alta",
    },
    {
        "city_display": "Bogotá", "name": "Maloka", "category": "atraccion", "zona": "Salitre",
        "dir": "Carrera 68D #24A-51, Bogotá, Colombia",
        "maps_query": "Maloka Bogotá",
        "lat": 4.6585, "lng": -74.1010,
        "descripcion": "Centro interactivo de ciencia y tecnología con cine domo — plan ideal en familia o con niños, sobre todo si el clima no acompaña.",
        "confianza": "media",
    },
    {
        "city_display": "Bogotá", "name": "Plaza de Bolívar", "category": "atraccion", "zona": "La Candelaria",
        "dir": "Carrera 7 #11-10, La Candelaria, Bogotá, Colombia",
        "maps_query": "Plaza de Bolívar Bogotá",
        "lat": 4.5981, "lng": -74.0760,
        "descripcion": "Corazón histórico y político: Catedral Primada, Capitolio y Palacio de Justicia alrededor. Punto de partida natural del recorrido por La Candelaria.",
        "confianza": "muy_alta",
    },
    {
        "city_display": "Bogotá", "name": "Chorro de Quevedo", "category": "atraccion", "zona": "La Candelaria",
        "dir": "Calle 12B #2-00, La Candelaria, Bogotá, Colombia",
        "maps_query": "Plaza del Chorro de Quevedo La Candelaria Bogotá",
        "lat": 4.5970, "lng": -74.0699,
        "descripcion": "Plazoleta donde la tradición ubica la fundación de Bogotá: ambiente bohemio, cuenteros, chicha y arte urbano. De día es seguro y encantador; de noche, ir acompañado.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Tour de grafiti por La Candelaria", "category": "experiencia", "zona": "La Candelaria",
        "dir": "Plaza de los Periodistas, La Candelaria, Bogotá, Colombia",
        "maps_query": "Bogotá Graffiti Tour La Candelaria",
        "lat": 4.5996, "lng": -74.0719,
        "descripcion": "Recorrido a pie por el arte urbano del centro — Bogotá es referente mundial de grafiti. Tours por propinas salen a diario; la mejor intro al barrio histórico y su historia reciente.",
        "confianza": "alta",
    },

    # ════════════ MIRADORES Y NATURALEZA ════════════
    {
        "city_display": "Bogotá", "name": "Cerro de Monserrate", "category": "mirador", "zona": "La Candelaria / Cerros",
        "dir": "Carrera 2 Este #21-48, Bogotá, Colombia",
        "maps_query": "Cerro de Monserrate Bogotá",
        "lat": 4.6058, "lng": -74.0557,
        "descripcion": "El mirador insignia de Bogotá (3.152 m): funicular o teleférico, santuario, vista de toda la sabana. Ideal al atardecer entre semana (menos fila). Plan del día 1.",
        "confianza": "muy_alta",
    },
    {
        "city_display": "Bogotá", "name": "Mirador Torre Colpatria", "category": "mirador", "zona": "Centro Internacional",
        "dir": "Carrera 7 #24-89, Bogotá, Colombia",
        "maps_query": "Torre Colpatria mirador Bogotá",
        "lat": 4.6125, "lng": -74.0703,
        "descripcion": "Vista de 360° desde 196 m en el primer rascacielos de la ciudad. Abre solo viernes, sábado, domingo y festivos — confirma horario antes de ir.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Quebrada La Vieja (senderismo)", "category": "experiencia", "zona": "Chapinero Alto / Cerros",
        "dir": "Carrera 1 con Calle 71, Bogotá, Colombia",
        "maps_query": "Sendero Sendero Quebrada La Vieja Bogotá",
        "lat": 4.6470, "lng": -74.0428,
        "descripcion": "Caminata matutina por los cerros orientales, dentro de la ciudad: bosque, agua y vistas. Abre temprano (cierra ~10–11 am) y suele requerir registro; gratis. Plan local muy querido para arrancar el día.",
        "confianza": "media_alta",
    },
    {
        "city_display": "Bogotá", "name": "Parque El Virrey", "category": "parque", "zona": "El Nogal / Chicó",
        "dir": "Calle 88 con Carrera 15, Bogotá, Colombia",
        "maps_query": "Parque El Virrey Bogotá",
        "lat": 4.6720, "lng": -74.0520,
        "descripcion": "Corredor verde lineal a lo largo de una quebrada en el norte — para caminar, trotar o pasear. Rodeado de cafés y restaurantes; muy seguro de día.",
        "confianza": "media_alta",
    },
    {
        "city_display": "Bogotá", "name": "Parque Nacional Enrique Olaya Herrera", "category": "parque", "zona": "La Macarena / Centro",
        "dir": "Carrera 7 con Calle 36, Bogotá, Colombia",
        "maps_query": "Parque Nacional Enrique Olaya Herrera Bogotá",
        "lat": 4.6195, "lng": -74.0660,
        "descripcion": "El parque urbano histórico de Bogotá, entre el centro y los cerros — senderos, fuentes y zonas verdes. Bonito de día, cerca de La Macarena y sus restaurantes.",
        "confianza": "media",
    },
    {
        "city_display": "Bogotá", "name": "Jardín Botánico José Celestino Mutis", "category": "parque", "zona": "Salitre",
        "dir": "Calle 63 #68-95, Bogotá, Colombia",
        "maps_query": "Jardín Botánico de Bogotá",
        "lat": 4.6685, "lng": -74.0995,
        "descripcion": "El jardín botánico de la ciudad: lago, palmetum, plantas de páramo y bosque andino. Plan tranquilo de medio día, ideal con buen clima.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Parque Metropolitano Simón Bolívar", "category": "parque", "zona": "Salitre",
        "dir": "Calle 53 con Carrera 48, Bogotá, Colombia",
        "maps_query": "Parque Simón Bolívar Bogotá",
        "lat": 4.6580, "lng": -74.0930,
        "descripcion": "El gran pulmón verde de Bogotá — lago, ciclorrutas y sede de grandes conciertos y festivales. Para caminar, hacer picnic o ejercicio.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Parque de la 93", "category": "parque", "zona": "Parque de la 93 (Chicó)",
        "dir": "Calle 93A con Carrera 13, Bogotá, Colombia",
        "maps_query": "Parque de la 93 Bogotá",
        "lat": 4.6766, "lng": -74.0487,
        "descripcion": "Parque rodeado de restaurantes, cafés y terrazas — plan tranquilo al aire libre o tarde de fotos, con eventos los fines de semana. Una de las zonas más seguras y agradables del norte.",
        "confianza": "muy_alta",
    },

    # ════════════ MERCADOS, LOCAL Y COMPRAS ════════════
    {
        "city_display": "Bogotá", "name": "Mercado de pulgas de Usaquén", "category": "mercado", "zona": "Usaquén",
        "dir": "Carrera 5 con Calle 119B, Usaquén, Bogotá, Colombia",
        "maps_query": "Mercado de las Pulgas Usaquén",
        "lat": 4.6952, "lng": -74.0312,
        "descripcion": "Mercado de antigüedades y artesanías, especialmente los domingos, en el casco colonial de Usaquén. Combínalo con brunch en la zona y la plaza.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Plaza de Mercado de Paloquemao", "category": "mercado", "zona": "Paloquemao",
        "dir": "Carrera 25 #19-20, Bogotá, Colombia",
        "maps_query": "Plaza de Mercado Paloquemao Bogotá",
        "lat": 4.6155, "lng": -74.0850,
        "descripcion": "La plaza de mercado más famosa de Bogotá: frutas exóticas, flores, hierbas y desayuno entre puestos. Ir temprano (antes de 9 am); experiencia gastronómica imperdible. Hay tours de frutas.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Plaza de Mercado La Perseverancia", "category": "mercado", "zona": "La Perseverancia / Centro",
        "dir": "Calle 30A #5-09, Bogotá, Colombia",
        "maps_query": "Plaza La Perseverancia Bogotá",
        "lat": 4.6178, "lng": -74.0668,
        "descripcion": "Plaza tradicional famosa por sus almuerzos caseros: sancocho, lechona, tamal. Auténtico y económico, muy local. Mejor al mediodía; barrio sencillo, ir de día.",
        "confianza": "media_alta",
    },
    {
        "city_display": "Bogotá", "name": "Centro Comercial Andino", "category": "compras", "zona": "Zona T",
        "dir": "Carrera 11 #82-71, Bogotá, Colombia",
        "maps_query": "Centro Comercial Andino Bogotá",
        "lat": 4.6669, "lng": -74.0540,
        "descripcion": "El mall de referencia de la Zona T: marcas internacionales y colombianas, conectado con El Retiro y Atlantis. Cómodo y seguro, con buena oferta de comida.",
        "confianza": "media_alta",
    },
    {
        "city_display": "Bogotá", "name": "Hacienda Santa Bárbara", "category": "compras", "zona": "Usaquén",
        "dir": "Carrera 7 #115-60, Usaquén, Bogotá, Colombia",
        "maps_query": "Hacienda Santa Bárbara Bogotá",
        "lat": 4.6970, "lng": -74.0335,
        "descripcion": "Centro comercial en una hacienda colonial del siglo XVIII — mezcla de tiendas y patrimonio. Bonito para pasear cerca de Usaquén.",
        "confianza": "media",
    },
    {
        "city_display": "Bogotá", "name": "Artesanías de Colombia (San Diego)", "category": "compras", "zona": "Centro Internacional",
        "dir": "Carrera 10 #26-50 (Plazoleta San Diego), Bogotá, Colombia",
        "maps_query": "Artesanías de Colombia San Diego Bogotá",
        "lat": 4.6118, "lng": -74.0688,
        "descripcion": "Tienda oficial de artesanías colombianas: mochilas wayúu, sombreros, cerámica, hamacas — con precio justo y origen garantizado. La forma segura de comprar artesanía auténtica sin que te 'tumben'.",
        "confianza": "media_alta",
    },

    # ════════════ EXPERIENCIAS LOCALES ════════════
    {
        "city_display": "Bogotá", "name": "Ciclovía dominical", "category": "experiencia", "zona": "Toda la ciudad",
        "dir": "Carrera 7 / Calle 26, Bogotá, Colombia",
        "maps_query": "Ciclovía Bogotá Carrera 7",
        "lat": 4.6280, "lng": -74.0660,
        "descripcion": "Domingos y festivos 7am–2pm, más de 120 km de vías se cierran a los carros para ciclistas, patinadores y peatones. Gratis y muy bogotano — alquila una bici y recorre la Carrera 7 o la Calle 26.",
        "confianza": "muy_alta",
    },
    {
        "city_display": "Bogotá", "name": "Tour en bici por Bogotá", "category": "experiencia", "zona": "La Candelaria / Centro",
        "dir": "La Candelaria, Bogotá, Colombia",
        "maps_query": "Bogotá Bike Tours La Candelaria",
        "lat": 4.5985, "lng": -74.0715,
        "descripcion": "Recorridos guiados en bicicleta que conectan el centro, plazas de mercado, grafiti y barrios — la mejor forma de entender la ciudad en medio día. Operadores reconocidos salen de La Candelaria.",
        "confianza": "media_alta",
    },

    # ════════════ EXCURSIONES (día completo, fuera de la ciudad) ════════════
    {
        "city_display": "Bogotá", "name": "Catedral de Sal de Zipaquirá", "category": "excursion", "zona": "Zipaquirá (afueras)",
        "dir": "Zipaquirá, Cundinamarca, Colombia",
        "maps_query": "Catedral de Sal de Zipaquirá",
        "lat": 5.0190, "lng": -73.9905,
        "descripcion": "Catedral subterránea excavada en una mina de sal, a ~1.5 h al norte. Día completo (combínala con el pueblo de Zipaquirá). Una de las excursiones clásicas desde Bogotá; hay tours o tren turístico los fines de semana.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Laguna de Guatavita", "category": "excursion", "zona": "Guatavita / Sesquilé (afueras)",
        "dir": "Sesquilé, Cundinamarca, Colombia",
        "maps_query": "Laguna de Guatavita",
        "lat": 5.0277, "lng": -73.7766,
        "descripcion": "La laguna sagrada muisca, origen de la leyenda de El Dorado, a ~1.5–2 h. Recorrido guiado por la reserva con vistas hermosas. Combínala con el pueblo de Guatavita.",
        "confianza": "media_alta",
    },
    {
        "city_display": "Bogotá", "name": "Mina de Sal de Nemocón", "category": "excursion", "zona": "Nemocón (afueras)",
        "dir": "Nemocón, Cundinamarca, Colombia",
        "maps_query": "Mina de Sal de Nemocón",
        "lat": 5.0680, "lng": -73.8790,
        "descripcion": "Alternativa más íntima y menos turística que Zipaquirá: túneles de sal con espejos de agua espectaculares (allí se grabó parte de la película '33'). Buen plan de día completo al norte.",
        "confianza": "media",
    },
    {
        "city_display": "Bogotá", "name": "Villa de Leyva", "category": "excursion", "zona": "Boyacá (afueras)",
        "dir": "Villa de Leyva, Boyacá, Colombia",
        "maps_query": "Villa de Leyva Boyacá",
        "lat": 5.6339, "lng": -73.5266,
        "descripcion": "Pueblo colonial con una de las plazas empedradas más grandes de América, a ~3.5–4 h. Ideal para quedarse una noche: viñedos, fósiles, desierto de la Candelaria. Plan de fin de semana, no de día.",
        "confianza": "media_alta",
    },
    {
        "city_display": "Bogotá", "name": "Parque Natural Chicaque", "category": "excursion", "zona": "San Antonio del Tequendama (afueras)",
        "dir": "San Antonio del Tequendama, Cundinamarca, Colombia",
        "maps_query": "Parque Natural Chicaque",
        "lat": 4.6090, "lng": -74.3050,
        "descripcion": "Bosque de niebla a ~1 h al suroccidente: senderos, cabañas en los árboles y aire de páramo. Naturaleza de verdad sin alejarse mucho; ideal para un día de caminata.",
        "confianza": "media",
    },
    {
        "city_display": "Bogotá", "name": "Suesca (senderismo y escalada)", "category": "excursion", "zona": "Suesca (afueras)",
        "dir": "Suesca, Cundinamarca, Colombia",
        "maps_query": "Rocas de Suesca",
        "lat": 5.1030, "lng": -73.7960,
        "descripcion": "La meca de la escalada en roca cerca de Bogotá (~1.5 h), con paredes a la orilla del río y rutas para principiantes. También se puede solo caminar. Plan de aventura de un día.",
        "confianza": "media",
    },

    # ════════════ AMPLIACIÓN (sesión de expansión) ════════════
    {
        "city_display": 'Bogotá',
        "name": 'Selma',
        "category": 'restaurante',
        "zona": 'Chapinero',
        "dir": 'Bogotá, Colombia',
        "maps_query": 'Selma restaurante Bogotá Chapinero',
        "lat": 4.644,
        "lng": -74.063,
        "descripcion": "Nueva entrada #96 en Latin America's 50 Best 2025. El segundo proyecto de Álvaro Clavijo (El Chato), en una casa restaurada de Chapinero. El chef Esteban Olaya reinterpreta clásicos colombianos con producto local. Reservar.",
        "confianza": 'muy_alta',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Debora',
        "category": 'restaurante',
        "zona": 'Chapinero',
        "dir": 'Bogotá, Colombia',
        "maps_query": 'Debora restaurante Bogotá',
        "lat": 4.645,
        "lng": -74.0625,
        "descripcion": "#85 en la lista extendida de Latin America's 50 Best 2025. Del chef Jacobo Bonilla: hiperestacionalidad y producto colombiano en platos coloridos y precisos. Una de las cocinas jóvenes más interesantes de la ciudad.",
        "confianza": 'muy_alta',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Villanos en Bermudas',
        "category": 'restaurante',
        "zona": 'Chapinero Alto',
        "dir": 'Carrera 4 #57-52, Bogotá, Colombia',
        "maps_query": 'Villanos en Bermudas Bogotá',
        "lat": 4.642,
        "lng": -74.0605,
        "descripcion": 'Cocina de autor sin etiquetas, atrevida y técnica, de los chefs Nicolás López y Sergio Meza. Ambiente joven y de culto entre foodies bogotanos. Ideal para una cena con personalidad.',
        "confianza": 'alta',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Cuzco',
        "category": 'restaurante',
        "zona": 'Parque de la 93',
        "dir": 'Carrera 13 #93A-31, Bogotá, Colombia',
        "maps_query": 'Cuzco Cocina Peruana Parque 93 Bogotá',
        "lat": 4.676,
        "lng": -74.048,
        "descripcion": 'Alta cocina peruana en el Parque de la 93: ceviches, tiraditos y platos de fondo con producto fresco. Ambiente elegante, ideal para almuerzo de negocios o cena. Una de las mejores propuestas peruanas de la ciudad.',
        "confianza": 'alta',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Osaka',
        "category": 'restaurante',
        "zona": 'Zona T / El Retiro',
        "dir": 'Carrera 13 #85-32, Bogotá, Colombia',
        "maps_query": 'Osaka Nikkei restaurante Bogotá',
        "lat": 4.668,
        "lng": -74.054,
        "descripcion": 'Cocina nikkei (fusión japonesa-peruana) de la reconocida cadena latinoamericana. Tiraditos, makis y platos de wok en ambiente sofisticado. Un clásico para los amantes del sushi de autor.',
        "confianza": 'alta',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Gordo',
        "category": 'restaurante',
        "zona": 'Chapinero Alto',
        "dir": 'Carrera 4 #66-84, Bogotá, Colombia',
        "maps_query": 'Gordo restaurante Chapinero Bogotá',
        "lat": 4.65,
        "lng": -74.0598,
        "descripcion": 'Restaurante de barrio con cocina de producto a la brasa, vinos naturales y ambiente relajado en Chapinero Alto. Favorito de la escena local por su carta corta que cambia seguido.',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Misia',
        "category": 'restaurante',
        "zona": 'Zona G',
        "dir": 'Carrera 7 #67-39, Bogotá, Colombia',
        "maps_query": 'Misia Leonor Espinosa restaurante Bogotá',
        "lat": 4.656,
        "lng": -74.0575,
        "descripcion": 'La propuesta casual de Leonor Espinosa (Leo): cocina popular colombiana de mar y región — cazuelas, fritos, sabores del Pacífico y Caribe — en un ambiente alegre y colorido. Más accesible que Leo, igual de sabroso.',
        "confianza": 'alta',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Mistral',
        "category": 'restaurante',
        "zona": 'Quinta Camacho',
        "dir": 'Carrera 8 #69-30, Bogotá, Colombia',
        "maps_query": 'Mistral restaurante Quinta Camacho Bogotá',
        "lat": 4.653,
        "lng": -74.0598,
        "descripcion": 'Brasserie de inspiración mediterránea en una casa de Quinta Camacho. Buena para desayunos, almuerzos y planes de día con producto fresco y panadería propia.',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Di Lucca',
        "category": 'restaurante',
        "zona": 'Zona G / Parque 93',
        "dir": 'Carrera 13 #85-32, Bogotá, Colombia',
        "maps_query": 'Di Lucca restaurante italiano Bogotá',
        "lat": 4.6675,
        "lng": -74.0535,
        "descripcion": 'Italiano clásico y confiable, muy querido por los bogotanos para reuniones familiares. Pastas, risottos y pizzas en porciones generosas. Ambiente cálido tipo trattoria.',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Watakushi',
        "category": 'restaurante',
        "zona": 'Zona T',
        "dir": 'Carrera 12 #83-17, Bogotá, Colombia',
        "maps_query": 'Watakushi sushi Bogotá',
        "lat": 4.6678,
        "lng": -74.053,
        "descripcion": 'Sushi y cocina asiática contemporánea con coctelería, en plena Zona T. Ambiente animado, ideal para cena previa a salir. Popular entre el público joven y de negocios.',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'La Cervecería Libre',
        "category": 'restaurante',
        "zona": 'Chapinero Alto',
        "dir": 'Carrera 4 #57-22, Bogotá, Colombia',
        "maps_query": 'La Cervecería Libre Bogotá',
        "lat": 4.6418,
        "lng": -74.0608,
        "descripcion": 'Cervecería artesanal con cocina de acompañamiento en Chapinero. Buen punto para tarde-noche informal con cervezas locales y ambiente de barrio.',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Capital Cocina',
        "category": 'restaurante',
        "zona": 'La Candelaria',
        "dir": 'Calle 10 #2-99, La Candelaria, Bogotá, Colombia',
        "maps_query": 'Capital Cocina restaurante Candelaria Bogotá',
        "lat": 4.5965,
        "lng": -74.073,
        "descripcion": 'Cocina colombiana contemporánea en una casa de La Candelaria, opción confiable y de buen sabor en pleno centro histórico. Ideal tras visitar los museos.',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Varietale',
        "category": 'cafe',
        "zona": 'Chapinero / Zona G',
        "dir": 'Bogotá, Colombia',
        "maps_query": 'Varietale café especialidad Bogotá',
        "lat": 4.656,
        "lng": -74.06,
        "descripcion": 'Punto de encuentro de la comunidad cafetera: aquí se corren competencias como la Barista League. Café de especialidad de altísimo nivel y ambiente para aficionados. Métodos de filtrado y espresso de primera.',
        "confianza": 'alta',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Devoción',
        "category": 'cafe',
        "zona": 'Zona G / Chapinero',
        "dir": 'Carrera 6 #66-25, Bogotá, Colombia',
        "maps_query": 'Devoción Coffee Bogotá Chapinero',
        "lat": 4.6575,
        "lng": -74.0585,
        "descripcion": 'Tuesta granos frescos de finca a taza, con sede también en Nueva York. Espacio de diseño cálido, ideal para trabajar o una pausa. Café colombiano trazable y de gran calidad.',
        "confianza": 'alta',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Café San Alberto (Candelaria)',
        "category": 'cafe',
        "zona": 'La Candelaria',
        "dir": 'Calle 11 #2-94, La Candelaria, Bogotá, Colombia',
        "maps_query": 'Café San Alberto La Candelaria Bogotá',
        "lat": 4.597,
        "lng": -74.0735,
        "descripcion": 'El café más premiado de Colombia, con catas guiadas en pleno centro histórico. Experiencia de degustación premium ideal para entender el café colombiano. A pasos de la Plaza de Bolívar.',
        "confianza": 'alta',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Arte y Pasión Café',
        "category": 'cafe',
        "zona": 'Centro / Chapinero',
        "dir": 'Carrera 7 #57-23, Bogotá, Colombia',
        "maps_query": 'Arte y Pasión Café Bogotá',
        "lat": 4.642,
        "lng": -74.0625,
        "descripcion": 'Campeones nacionales de barismo y latte art. Café de especialidad con técnica impecable y talleres. Para quien quiere ver el oficio del barista en su mejor nivel.',
        "confianza": 'alta',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Café Quindío Premium',
        "category": 'cafe',
        "zona": 'Usaquén / Norte',
        "dir": 'Bogotá, Colombia',
        "maps_query": 'Café Quindío Bogotá',
        "lat": 4.695,
        "lng": -74.032,
        "descripcion": 'Tienda-café de la marca del Eje Cafetero con producto de origen y repostería. Buena opción para llevar café a casa y probar bebidas clásicas en ambiente cálido.',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'La Sala de Laura',
        "category": 'bar',
        "zona": 'Chapinero',
        "dir": 'Bogotá, Colombia',
        "maps_query": 'La Sala de Laura bar Bogotá',
        "lat": 4.644,
        "lng": -74.0635,
        "descripcion": "#68 en The World's 50 Best Bars 2025 — el mejor bar de Bogotá. Coctelería de autor que exalta la bioculturalidad colombiana: cada piso es una experiencia, terminando en un rooftop con ingredientes de la finca de los dueños. Imperdible para amantes del cóctel.",
        "confianza": 'muy_alta',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Astoria Rooftop',
        "category": 'bar',
        "zona": 'Zona T',
        "dir": 'AC Hotel Bogotá Zona T, Carrera 13 #85-32, Bogotá, Colombia',
        "maps_query": 'Astoria Sky Bar Bogotá Zona Rosa',
        "lat": 4.668,
        "lng": -74.0535,
        "descripcion": 'Rooftop sofisticado en el AC Hotel by Marriott (Zona T), 15 pisos sobre la ciudad. Coctelería de autor, cocina internacional y vistas a los cerros. Ambiente tipo lounge neoyorquino para empezar la noche con estilo.',
        "confianza": 'alta',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Federal Rooftop',
        "category": 'bar',
        "zona": 'Zona Rosa / El Retiro',
        "dir": 'Calle 81 #11-94, Bogotá, Colombia',
        "maps_query": 'Federal Rooftop bar Zona Rosa Bogotá',
        "lat": 4.6665,
        "lng": -74.054,
        "descripcion": 'Rooftop enérgico en la Zona Rosa con DJ desde las 9pm, brunch los sábados y ambiente festivo. Para mezclar tragos con fiesta — martini de maracuyá y mojitos helados son los favoritos.',
        "confianza": 'alta',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Sky 15 Rooftop',
        "category": 'bar',
        "zona": 'Chapinero',
        "dir": 'Hilton Bogotá, Carrera 7 #72-41, Bogotá, Colombia',
        "maps_query": 'Sky 15 Rooftop Hilton Bogotá',
        "lat": 4.6555,
        "lng": -74.057,
        "descripcion": 'En el techo del Hilton, 54 m sobre Chapinero, con vista de 360° al skyline. Cocteles únicos y parrilla, a veces con DJ. Sofisticado y exclusivo, abierto al público.',
        "confianza": 'alta',
    },
    {
        "city_display": 'Bogotá',
        "name": 'El Mono Bandido',
        "category": 'bar',
        "zona": 'Chapinero / Norte',
        "dir": 'Calle 127, Bogotá, Colombia',
        "maps_query": 'El Mono Bandido cervecería Bogotá',
        "lat": 4.696,
        "lng": -74.042,
        "descripcion": 'Cervecería moderna de ambiente tropical y relajado, con amplia carta de artesanales (Lager, Ale, sidra), cócteles y comida casera. Famoso por su dinámica de mensajes en servilletas entre mesas.',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Catedral Primada de Colombia',
        "category": 'atraccion',
        "zona": 'La Candelaria / Plaza de Bolívar',
        "dir": 'Carrera 7 #10-80, Plaza de Bolívar, Bogotá, Colombia',
        "maps_query": 'Catedral Primada de Colombia Bogotá',
        "lat": 4.598,
        "lng": -74.0755,
        "descripcion": 'La catedral principal del país, sobre la Plaza de Bolívar. Arquitectura neoclásica imponente y centro de la vida religiosa de Bogotá. Parada obligada al recorrer el centro histórico.',
        "confianza": 'alta',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Iglesia de San Francisco',
        "category": 'atraccion',
        "zona": 'Centro / Av. Jiménez',
        "dir": 'Carrera 7 con Av. Jiménez, Bogotá, Colombia',
        "maps_query": 'Iglesia de San Francisco Bogotá',
        "lat": 4.6015,
        "lng": -74.072,
        "descripcion": 'La iglesia más antigua de Bogotá (s. XVII), famosa por su altar mayor dorado barroco, uno de los más bellos del país. Pequeña joya en pleno centro, junto al Museo del Oro.',
        "confianza": 'alta',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Centro Cultural Gabriel García Márquez',
        "category": 'atraccion',
        "zona": 'La Candelaria',
        "dir": 'Calle 11 #5-60, La Candelaria, Bogotá, Colombia',
        "maps_query": 'Centro Cultural Gabriel García Márquez Bogotá',
        "lat": 4.5975,
        "lng": -74.0735,
        "descripcion": 'Diseñado por Rogelio Salmona, alberga librería del FCE, exposiciones y vista al centro. Arquitectura en ladrillo emblemática. Buen alto cultural en plena Candelaria.',
        "confianza": 'alta',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Museo de Bogotá',
        "category": 'atraccion',
        "zona": 'La Candelaria',
        "dir": 'Carrera 4 #10-18, La Candelaria, Bogotá, Colombia',
        "maps_query": 'Museo de Bogotá Casa Sámano',
        "lat": 4.597,
        "lng": -74.0728,
        "descripcion": 'Cuenta la historia y transformación de la ciudad a través de exposiciones en una casa colonial. Ideal para entender Bogotá antes de recorrerla.',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Planetario de Bogotá',
        "category": 'atraccion',
        "zona": 'Centro Internacional',
        "dir": 'Calle 26B #5-93, Bogotá, Colombia',
        "maps_query": 'Planetario de Bogotá',
        "lat": 4.616,
        "lng": -74.07,
        "descripcion": 'Domo proyección astronómica, museo del espacio y exposiciones, junto al Parque de la Independencia. Plan familiar y cultural en el centro.',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Casa de Nariño',
        "category": 'atraccion',
        "zona": 'La Candelaria',
        "dir": 'Carrera 8 #7-26, Bogotá, Colombia',
        "maps_query": 'Casa de Nariño Palacio Presidencial Bogotá',
        "lat": 4.5955,
        "lng": -74.076,
        "descripcion": 'El palacio presidencial de Colombia. Se puede ver el cambio de guardia y, con reserva previa, hacer recorridos. Arquitectura neoclásica imponente en el corazón del poder.',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Parque de los Novios',
        "category": 'parque',
        "zona": 'Norte / Av. 68',
        "dir": 'Calle 63 con Autopista Norte, Bogotá, Colombia',
        "maps_query": 'Parque de los Novios Bogotá',
        "lat": 4.668,
        "lng": -74.078,
        "descripcion": 'Parque con lago donde se pueden alquilar botes, zonas verdes y trote. Tranquilo y popular entre familias los fines de semana. Buen respiro verde en el norte.',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Parque El Chicó (Museo)',
        "category": 'parque',
        "zona": 'Chicó / Norte',
        "dir": 'Carrera 7 #93-01, Bogotá, Colombia',
        "maps_query": 'Parque Museo El Chicó Bogotá',
        "lat": 4.677,
        "lng": -74.048,
        "descripcion": 'Jardines de una antigua hacienda colonial convertida en museo, oasis verde junto al Parque de la 93. Entrada tranquila para un paseo y un café en el norte.',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Mirador de La Calera',
        "category": 'mirador',
        "zona": 'La Calera (afueras)',
        "dir": 'Vía La Calera, Bogotá, Colombia',
        "maps_query": 'Mirador de La Calera Bogotá',
        "lat": 4.705,
        "lng": -74.015,
        "descripcion": 'Subiendo por la vía a La Calera, varios miradores regalan la vista nocturna de Bogotá iluminada. Plan clásico de atardecer/noche; hay restaurantes y fogatas en el trayecto. Ir en carro o taxi.',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Cerro El Cable (senderismo)',
        "category": 'experiencia',
        "zona": 'Chapinero Alto (cerros)',
        "dir": 'Sendero El Cable, Bogotá, Colombia',
        "maps_query": 'Sendero Cerro El Cable Bogotá',
        "lat": 4.638,
        "lng": -74.042,
        "descripcion": 'Sendero de montaña por los cerros orientales con vistas a la ciudad. Caminata exigente y gratificante; ir temprano y consultar horarios de acceso (suele abrir mañanas). Llevar agua y ropa de clima cambiante.',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Parque Simón Bolívar — Lago',
        "category": 'parque',
        "zona": 'Salitre / Centro-Occidente',
        "dir": 'Calle 53 con Carrera 48, Bogotá, Colombia',
        "maps_query": 'Lago Parque Simón Bolívar Bogotá',
        "lat": 4.658,
        "lng": -74.093,
        "descripcion": 'El gran pulmón de Bogotá (más grande que Central Park): lago con botes, ciclovía, conciertos y picnic. Plan de día al aire libre. (Si ya tienes el parque general, esta es la zona del lago.)',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Centro Comercial El Retiro',
        "category": 'compras',
        "zona": 'Zona T / El Retiro',
        "dir": 'Calle 82 #11-75, Bogotá, Colombia',
        "maps_query": 'Centro Comercial El Retiro Bogotá',
        "lat": 4.6675,
        "lng": -74.0545,
        "descripcion": 'Centro comercial de alta gama en plena Zona T, con marcas de lujo, restaurantes y terraza. Punto de encuentro elegante para compras y comer en el corazón de la zona rosa.',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Mercado de las Pulgas de San Alejo',
        "category": 'mercado',
        "zona": 'Centro Internacional',
        "dir": 'Carrera 7 con Calle 24, Bogotá, Colombia',
        "maps_query": 'Mercado de las Pulgas San Alejo Bogotá',
        "lat": 4.612,
        "lng": -74.069,
        "descripcion": 'Mercado de pulgas dominical icónico: antigüedades, vinilos, monedas, curiosidades y artesanía. Plan de domingo para buscar tesoros y empaparse de Bogotá local.',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Sorella',
        "category": 'restaurante',
        "zona": 'Chapinero',
        "dir": 'Bogotá, Colombia',
        "maps_query": 'Sorella restaurante italiano Chapinero Bogotá',
        "lat": 4.644,
        "lng": -74.062,
        "descripcion": 'Cocina italiana reinventada en Chapinero: pasta fresca hecha en casa (agnolotti de provolone con hongos) y pizzas de masa cuidada. Ambiente acogedor, muy recomendado para una cena tranquila.',
        "confianza": 'alta',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Fiero',
        "category": 'restaurante',
        "zona": 'Zona G',
        "dir": 'Bogotá, Colombia',
        "maps_query": 'Fiero parrilla uruguaya Zona G Bogotá',
        "lat": 4.6565,
        "lng": -74.058,
        "descripcion": 'Parrilla uruguaya referente para los amantes de la carne: cortes a la brasa de excelente calidad y buen servicio. Plan ideal para carnívoros en la Zona G.',
        "confianza": 'alta',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Insurgentes',
        "category": 'restaurante',
        "zona": 'Zona G',
        "dir": 'Bogotá, Colombia',
        "maps_query": 'Insurgentes tacos mexicanos Bogotá',
        "lat": 4.6558,
        "lng": -74.0585,
        "descripcion": 'Tacos con auténtico sabor mexicano, servicio rápido y ambiente para quedarse a tomar cervezas con amigos. De los mejores mexicanos casuales de la ciudad.',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Cecilia',
        "category": 'restaurante',
        "zona": 'Usaquén',
        "dir": 'Calle 117 #6A-60, Usaquén, Bogotá, Colombia',
        "maps_query": 'Cecilia restaurante italiano Usaquén Bogotá',
        "lat": 4.696,
        "lng": -74.031,
        "descripcion": 'Italiano de pasta, pizza y entradas notables en Usaquén — buena apuesta para citas, cenas y celebraciones. Ambiente cálido y servicio cuidado.',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Armadillo',
        "category": 'restaurante',
        "zona": 'Zona G',
        "dir": 'Bogotá, Colombia',
        "maps_query": 'Armadillo parrilla restaurante Bogotá',
        "lat": 4.6562,
        "lng": -74.0578,
        "descripcion": 'Parrilla de ambiente elegante y cálido, ideal para una cena romántica. Carnes a la brasa con buen punto. Un clásico confiable de carnes en Bogotá.',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Wok',
        "category": 'restaurante',
        "zona": 'Varias sedes / Parque 93',
        "dir": 'Bogotá, Colombia',
        "maps_query": 'Wok restaurante asiático Bogotá',
        "lat": 4.676,
        "lng": -74.047,
        "descripcion": 'Cadena local de cocina asiática (tailandesa, japonesa, vietnamita) con foco en producto sostenible y pesca responsable. Confiable, fresca y de buen precio. Varias sedes en la ciudad.',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Quinua y Amaranto',
        "category": 'restaurante',
        "zona": 'La Candelaria',
        "dir": 'Calle 11 #2-95, La Candelaria, Bogotá, Colombia',
        "maps_query": 'Quinua y Amaranto restaurante vegetariano Candelaria Bogotá',
        "lat": 4.5968,
        "lng": -74.0732,
        "descripcion": 'Restaurante vegetariano clásico de La Candelaria con menú del día casero y saludable. Acogedor y económico, favorito en el centro histórico. Ideal tras los museos.',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Pajares Salinas',
        "category": 'restaurante',
        "zona": 'Chico / Norte',
        "dir": 'Carrera 10 #96-08, Bogotá, Colombia',
        "maps_query": 'Pajares Salinas restaurante español Bogotá',
        "lat": 4.684,
        "lng": -74.048,
        "descripcion": 'Restaurante español tradicional, institución bogotana desde 1956: paellas, cochinillo y mariscos en ambiente clásico. Para una comida formal de sabores ibéricos.',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Abasto',
        "category": 'restaurante',
        "zona": 'Usaquén / Quinta Camacho',
        "dir": 'Carrera 6 #119B-52, Usaquén, Bogotá, Colombia',
        "maps_query": 'Abasto Usaquén restaurante Bogotá',
        "lat": 4.697,
        "lng": -74.03,
        "descripcion": 'Cocina de mercado con producto fresco del campo colombiano: desayunos célebres, huevos campesinos y panadería propia. Muy querido para brunch de fin de semana.',
        "confianza": 'alta',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Masa (Quinta Camacho)',
        "category": 'cafe',
        "zona": 'Quinta Camacho',
        "dir": 'Calle 70 #4-83, Bogotá, Colombia',
        "maps_query": 'Masa panadería Quinta Camacho Bogotá',
        "lat": 4.653,
        "lng": -74.06,
        "descripcion": 'Panadería y brunch de culto: pan de masa madre, pastelería y desayunos generosos. Filas los fines de semana por algo. (Si ya tienes Masa Rosales, esta es la sede de Quinta Camacho.)',
        "confianza": 'alta',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Bogotá Beer Company (Zona T)',
        "category": 'bar',
        "zona": 'Zona T',
        "dir": 'Carrera 12 #83-33, Bogotá, Colombia',
        "maps_query": 'Bogotá Beer Company Zona T Carrera 12 83',
        "lat": 4.6678,
        "lng": -74.0528,
        "descripcion": 'La cervecería artesanal más conocida de la ciudad (BBC), sede Zona T. Buen punto de after-office con cervezas propias y ambiente animado. (Distinto de El Cielo: este SÍ es BBC.)',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Smoking Molly',
        "category": 'bar',
        "zona": 'Chapinero',
        "dir": 'Carrera 9 #59-08, Bogotá, Colombia',
        "maps_query": 'Smoking Molly Bogotá',
        "lat": 4.644,
        "lng": -74.064,
        "descripcion": 'Bar de rock y cervezas con ambiente desenfadado en Chapinero. Buena música, hamburguesas y plan de noche relajado lejos de lo pretencioso.',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Cementerio Central',
        "category": 'atraccion',
        "zona": 'Centro',
        "dir": 'Carrera 20 #24-80, Bogotá, Colombia',
        "maps_query": 'Cementerio Central Bogotá',
        "lat": 4.6175,
        "lng": -74.079,
        "descripcion": 'Monumento nacional con mausoleos históricos y arte funerario; recorrer su historia es un plan cultural distinto. Cerca, el barrio de la Macarena ofrece arte y cafés.',
        "confianza": 'media',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Barrio La Macarena',
        "category": 'atraccion',
        "zona": 'La Macarena / Centro',
        "dir": 'La Macarena, Bogotá, Colombia',
        "maps_query": 'Barrio La Macarena Bogotá',
        "lat": 4.612,
        "lng": -74.067,
        "descripcion": 'Barrio bohemio de galerías de arte, restaurantes de autor y cafés, a los pies de los cerros. Perfecto para caminar, comer distinto y ver arte contemporáneo. Ambiente local y creativo.',
        "confianza": 'alta',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Usaquén (centro histórico)',
        "category": 'atraccion',
        "zona": 'Usaquén',
        "dir": 'Usaquén, Bogotá, Colombia',
        "maps_query": 'Usaquén plaza centro Bogotá',
        "lat": 4.695,
        "lng": -74.0305,
        "descripcion": 'Antiguo pueblo colonial absorbido por la ciudad: plaza, iglesia, calles adoquinadas, restaurantes y el famoso mercado de pulgas dominical. Plan de día completo en el norte.',
        "confianza": 'alta',
    },
    {
        "city_display": 'Bogotá',
        "name": 'Monumento a los Héroes / Zona',
        "category": 'atraccion',
        "zona": 'Norte-Centro',
        "dir": 'Calle 80 con Autopista Norte, Bogotá, Colombia',
        "maps_query": 'Monumento Banderas Bogotá',
        "lat": 4.665,
        "lng": -74.064,
        "descripcion": 'Hito urbano y punto de referencia para ubicarse en la ciudad. Útil como nodo de transporte y orientación más que como visita en sí.',
        "confianza": 'baja',
    },

    # ════════════ INFRAESTRUCTURA PARA EL VIAJERO ════════════
    # Clínicas / urgencias — 24 horas, todas con teléfono verificado (jun. 2026)

    {
        "city_display": "Bogotá", "name": "Fundación Santa Fe de Bogotá",
        "category": "clinica", "zona": "Usaquén / Norte",
        "dir": "Calle 119 #7-75, Bogotá, Colombia",
        "maps_query": "Fundación Santa Fe de Bogotá hospital",
        "lat": 4.6960, "lng": -74.0330,
        "descripcion": "El hospital privado mejor calificado de Colombia (Newsweek). Urgencias 24h en 3 pisos (adultos, ortopedia, pediatría). Tel. urgencias: +57 601 603-0303 · +57 601 482-4488. Acepta seguros internacionales incluyendo CIGNA. Emergencias Colombia: 123.",
        "confianza": "muy_alta",
    },
    {
        "city_display": "Bogotá", "name": "Clínica del Country",
        "category": "clinica", "zona": "Chicó / Norte",
        "dir": "Carrera 16 #82-57, Bogotá, Colombia",
        "maps_query": "Clínica del Country urgencias Bogotá",
        "lat": 4.6660, "lng": -74.0500,
        "descripcion": "Clínica de referencia en el norte, más de 60 años de historia. Urgencias adultos y pediátricas 24h. Tel.: +57 601 390-5099 · +57 601 390-4887. Reconocida por Newsweek y certificada por ICONTEC. Emergencias Colombia: 123.",
        "confianza": "muy_alta",
    },
    {
        "city_display": "Bogotá", "name": "Clínica Shaio",
        "category": "clinica", "zona": "Norte (Suba)",
        "dir": "Diagonal 115A #70C-75, Bogotá, Colombia",
        "maps_query": "Clínica Shaio urgencias Bogotá",
        "lat": 4.7040, "lng": -74.0730,
        "descripcion": "Especializada en cardiología y neurología, urgencias 24h de alta complejidad. Tel.: +57 601 593-8210. Una de las mejores para emergencias cardiovasculares. Emergencias Colombia: 123.",
        "confianza": "muy_alta",
    },
    {
        "city_display": "Bogotá", "name": "Clínica Reina Sofía",
        "category": "clinica", "zona": "Usaquén / Norte",
        "dir": "Avenida Calle 127 #20-56, Bogotá, Colombia",
        "maps_query": "Clínica Reina Sofía urgencias Bogotá",
        "lat": 4.7000, "lng": -74.0440,
        "descripcion": "Clínica de Colsanitas, alta complejidad, urgencias 24h. Tel.: +57 601 625-2111. Norte de la ciudad, accesible para viajeros hospedados en Chapinero o Usaquén. Emergencias Colombia: 123.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Hospital Universitario San Ignacio",
        "category": "clinica", "zona": "Centro / La Candelaria",
        "dir": "Carrera 7 #40-62, Bogotá, Colombia",
        "maps_query": "Hospital San Ignacio Bogotá urgencias",
        "lat": 4.6275, "lng": -74.0655,
        "descripcion": "Hospital universitario de alta complejidad en el centro, referente académico y clínico. Urgencias 24h. Tel.: +57 601 594-6161. Mejor opción de urgencias para viajeros en La Candelaria o Chapinero sur. Emergencias Colombia: 123.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Fundación Cardioinfantil",
        "category": "clinica", "zona": "Norte (Usaquén)",
        "dir": "Calle 163A #13B-60, Bogotá, Colombia",
        "maps_query": "Fundación Cardioinfantil hospital Bogotá",
        "lat": 4.7320, "lng": -74.0400,
        "descripcion": "Hospital de alta complejidad especializado en cardiología y pediatría. Urgencias 24h. Tel.: +57 601 667-2727. Norte extremo de la ciudad. Emergencias Colombia: 123.",
        "confianza": "alta",
    },

    # Supermercados — principales en zonas de viajeros

    {
        "city_display": "Bogotá", "name": "Carulla Quinta Camacho",
        "category": "supermercado", "zona": "Quinta Camacho / Zona G",
        "dir": "Carrera 10A #70-37, Bogotá, Colombia",
        "maps_query": "Carulla Quinta Camacho Bogotá",
        "lat": 4.6530, "lng": -74.0590,
        "descripcion": "Supermercado premium en plena Zona G, a pasos de los restaurantes de autor. Lun–Sáb 6am–10:30pm, Dom 7am–9pm. Tel.: +57 601 746-8888. Para comprar vinos, quesos, snacks y artículos de calidad.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Carulla Calle 85",
        "category": "supermercado", "zona": "Chicó / Parque 93",
        "dir": "Avenida Calle 85 #15-29, Bogotá, Colombia",
        "maps_query": "Carulla Calle 85 Bogotá",
        "lat": 4.6720, "lng": -74.0490,
        "descripcion": "Supermercado premium junto al Parque de la 93. Lun–Sáb 6:30am–10pm. Todo lo que el viajero necesita en zona de hoteles de lujo y restaurantes.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Carulla Candelaria / Centro",
        "category": "supermercado", "zona": "La Candelaria / Centro",
        "dir": "Calle 19 #5-30, Bogotá, Colombia",
        "maps_query": "Carulla Calle 19 Centro Bogotá",
        "lat": 4.6030, "lng": -74.0715,
        "descripcion": "Carulla en pleno centro histórico. Lun–Sáb 7am–10pm, Dom 7am–9pm. Opción de supermercado de calidad para viajeros alojados en La Candelaria.",
        "confianza": "media",
    },
    {
        "city_display": "Bogotá", "name": "Éxito Chapinero",
        "category": "supermercado", "zona": "Chapinero",
        "dir": "Avenida Caracas #53-46, Bogotá, Colombia",
        "maps_query": "Éxito Chapinero Bogotá supermercado",
        "lat": 4.6380, "lng": -74.0650,
        "descripcion": "Hipermercado grande con todo tipo de productos, electrónica y ropa. El más completo de Chapinero. Lun–Dom 8am–10pm. Para compras de mayor volumen.",
        "confianza": "media",
    },
    {
        "city_display": "Bogotá", "name": "D1 (Chapinero Alto)",
        "category": "supermercado", "zona": "Chapinero Alto",
        "dir": "Carrera 5 #60-10, Bogotá, Colombia",
        "maps_query": "D1 supermercado Chapinero Bogotá",
        "lat": 4.6450, "lng": -74.0610,
        "descripcion": "Tienda de descuento colombiana, muy económica. Lo básico (agua, snacks, aseo) a muy buen precio. Varias sedes en Chapinero y norte. Lun–Dom 7am–9pm aprox.",
        "confianza": "media",
    },

    # Farmacias — cadenas con sedes en zonas turísticas

    {
        "city_display": "Bogotá", "name": "Cruz Verde (Chapinero / Zona G)",
        "category": "farmacia", "zona": "Chapinero / Zona G",
        "dir": "Calle 71A #5-90, Bogotá, Colombia",
        "maps_query": "Cruz Verde farmacia Chapinero Bogotá",
        "lat": 4.6558, "lng": -74.0575,
        "descripcion": "Farmacia Cruz Verde, cadena líder en Colombia. Domicilios: 486-5000 (Bogotá). Medicamentos, artículos de aseo y primeros auxilios. Lun–Sáb 7am–9pm, Dom 9am–6pm. Busca la sede más cercana en la app Cruz Verde.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Cruz Verde (Calle 127 / Norte)",
        "category": "farmacia", "zona": "Usaquén / Norte",
        "dir": "Avenida Calle 127 #21-60 local 101, Bogotá, Colombia",
        "maps_query": "Cruz Verde Calle 127 Usaquén Bogotá",
        "lat": 4.7005, "lng": -74.0445,
        "descripcion": "Cruz Verde abierta 24 horas en el norte — la opción cuando necesitas medicamentos de urgencia a cualquier hora. Domicilios: 486-5000. Cerca de Clínica Reina Sofía.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Farmacenter (Chapinero)",
        "category": "farmacia", "zona": "Chapinero",
        "dir": "Carrera 13 #66-95, Bogotá, Colombia",
        "maps_query": "Farmacenter Futurama Chapinero Bogotá",
        "lat": 4.6490, "lng": -74.0620,
        "descripcion": "Farmacia de cadena con amplio surtido en Chapinero. Lun–Dom 6am–10pm. Tel.: +57 313 858-3255. Para medicamentos, dermocosméticos y productos de salud.",
        "confianza": "media",
    },
    {
        "city_display": "Bogotá", "name": "Drogas La Rebaja (Centro)",
        "category": "farmacia", "zona": "La Candelaria / Centro",
        "dir": "Carrera 7 #12-40, Bogotá, Colombia",
        "maps_query": "Drogas La Rebaja Centro Bogotá",
        "lat": 4.5982, "lng": -74.0748,
        "descripcion": "Cadena de droguerías económica y extendida. La más fácil de encontrar en el centro histórico. Precios bajos para medicamentos genéricos y de venta libre.",
        "confianza": "media",
    },

    # Centros comerciales adicionales de referencia

    {
        "city_display": "Bogotá", "name": "Centro Comercial Unicentro",
        "category": "compras", "zona": "Norte (Usaquén)",
        "dir": "Avenida 15 #123-30, Bogotá, Colombia",
        "maps_query": "Centro Comercial Unicentro Bogotá",
        "lat": 4.6985, "lng": -74.0395,
        "descripcion": "Uno de los más grandes y tradicionales de Bogotá, en el norte. Tiendas de moda, cine, cajeros, restaurantes y zonas de juego. Buen punto de referencia y refugio cuando llueve. Lun–Dom 10am–9pm.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Centro Comercial Gran Estación",
        "category": "compras", "zona": "Salitre / Centro-Occidente",
        "dir": "Avenida El Dorado #65B-95, Bogotá, Colombia",
        "maps_query": "Centro Comercial Gran Estación Bogotá",
        "lat": 4.6458, "lng": -74.1098,
        "descripcion": "Gran centro comercial camino al aeropuerto El Dorado — ideal para compras de última hora antes de volar. Supermercado Éxito, cine, cajeros y restaurantes. Lun–Dom 10am–9pm.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Centro Comercial Santafé",
        "category": "compras", "zona": "Norte (Autopista)",
        "dir": "Autopista Norte #227-51, Bogotá, Colombia",
        "maps_query": "Centro Comercial Santafé Bogotá",
        "lat": 4.7560, "lng": -74.0420,
        "descripcion": "Uno de los más grandes del país, extremo norte. Tiendas internacionales (Zara, H&M, Falabella), cine, cajeros y gastronomía. Útil si te alojas en el norte o antes de excursiones por esa vía.",
        "confianza": "media",
    },

    # Transporte — nodos clave para el viajero

    {
        "city_display": "Bogotá", "name": "Aeropuerto El Dorado (BOG)",
        "category": "transporte", "zona": "Fontibón / Occidente",
        "dir": "Avenida El Dorado, Bogotá, Colombia",
        "maps_query": "Aeropuerto Internacional El Dorado Bogotá",
        "lat": 4.7016, "lng": -74.1469,
        "descripcion": "Aeropuerto internacional de Bogotá, el más grande de Colombia. Terminal 1 (internacional y la mayoría de vuelos), Terminal 2 (Avianca). Taxi oficial desde el aeropuerto: contratar en el counter dentro, no en la calle. Taxi a Chapinero/norte: ~50.000–80.000 COP según tráfico. TransMilenio Fase III llega a la estación El Dorado.",
        "confianza": "muy_alta",
    },
    {
        "city_display": "Bogotá", "name": "Terminal de Transportes de Bogotá",
        "category": "transporte", "zona": "Salitre / Centro-Occidente",
        "dir": "Diagonal 23 #69-11, Bogotá, Colombia",
        "maps_query": "Terminal de Transportes Bogotá buses",
        "lat": 4.6487, "lng": -74.1118,
        "descripcion": "Terminal principal de buses intermunicipales: salidas a Medellín, Cartagena, Villa de Leyva, Zipaquirá, etc. Módulos 1-5 según destino. Llegar con tiempo; taxis y Transmilenio disponibles.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "TransMilenio — Estación Calle 100",
        "category": "transporte", "zona": "Norte (Calle 100)",
        "dir": "Avenida Caracas con Calle 100, Bogotá, Colombia",
        "maps_query": "TransMilenio estación Calle 100 Bogotá",
        "lat": 4.6860, "lng": -74.0630,
        "descripcion": "Estación de TransMilenio de gran tráfico en el norte. Conexión rápida hacia el centro o el aeropuerto. El sistema cuesta ~$3.500 COP (tarjeta TuLlave recargable). Frecuencias altas en hora pico.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "TransMilenio — Estación Museo del Oro",
        "category": "transporte", "zona": "Centro",
        "dir": "Carrera 7 con Calle 16, Bogotá, Colombia",
        "maps_query": "TransMilenio estación Museo del Oro Bogotá",
        "lat": 4.6028, "lng": -74.0710,
        "descripcion": "Estación de TransMilenio en el centro histórico, junto al Museo del Oro. Punto de entrada/salida para La Candelaria y el centro. Conexión directa al Portal El Dorado (aeropuerto).",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Portal El Dorado (TransMilenio)",
        "category": "transporte", "zona": "Fontibón / Occidente",
        "dir": "Avenida El Dorado #105-60, Bogotá, Colombia",
        "maps_query": "Portal El Dorado TransMilenio Bogotá",
        "lat": 4.6975, "lng": -74.1265,
        "descripcion": "Terminal occidental de TransMilenio, a 5 min del aeropuerto en taxi (~$10.000 COP). Desde aquí el bus llega al centro en ~40 min por ~$3.500 COP. Alternativa económica al taxi desde el aeropuerto.",
        "confianza": "alta",
    },

    # ════════════ EXPANSIÓN 2 (tanda final) ════════════

    # ── Restaurantes adicionales ──
    {
        "city_display": "Bogotá", "name": "Salvo Patria",
        "category": "restaurante", "zona": "Chapinero Alto",
        "dir": "Calle 54A #4-13, Bogotá, Colombia",
        "maps_query": "Salvo Patria restaurante Chapinero Bogotá",
        "lat": 4.6415, "lng": -74.0608,
        "descripcion": "Cocina de territorio con ingredientes de productores colombianos, bajo el chef Alejandro Gutiérrez (ex Central Lima). Una de las propuestas más honestas y sólidas de Chapinero. Ambiente relajado, ideal para almuerzo. Tel.: +57 601 702-6367.",
        "confianza": "muy_alta",
    },
    {
        "city_display": "Bogotá", "name": "Pesquera Jaramillo",
        "category": "restaurante", "zona": "Usaquén / Santa Bárbara",
        "dir": "Calle 119B #6-20, Bogotá, Colombia",
        "maps_query": "Pesquera Jaramillo Santa Bárbara Bogotá",
        "lat": 4.6970, "lng": -74.0325,
        "descripcion": "La referencia de mariscos y pescados frescos en Bogotá — improbable a 2.600 m de altura, pero el frescor del producto lo hace posible. Ceviches, cazuelas y cazuelitas de mariscos. Muy popular; mejor con reserva.",
        "confianza": "muy_alta",
    },
    {
        "city_display": "Bogotá", "name": "Tábula",
        "category": "restaurante", "zona": "Zona G",
        "dir": "Calle 70 #4-27, Bogotá, Colombia",
        "maps_query": "Tábula restaurante Zona G Bogotá",
        "lat": 4.6548, "lng": -74.0587,
        "descripcion": "Cocina a la brasa con horno de leña y mesas largas para compartir, del chef Tomás Rueda. Ingredientes de temporada de productores locales, clara impronta mediterránea. Atmosfera cálida e informal, perfecto para grupos.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Oci.Mde",
        "category": "restaurante", "zona": "Chapinero Alto",
        "dir": "Carrera 5 #57-12, Bogotá, Colombia",
        "maps_query": "Oci Mde Chapinero Bogotá",
        "lat": 4.6428, "lng": -74.0608,
        "descripcion": "Restaurante antioqueño de autor: el sabor de la cocina paisa revisado con técnica y producto fresco. Uno de los más queridos de Chapinero Alto por su comodidad y consistencia. Reservar.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "La Bifería",
        "category": "restaurante", "zona": "Norte (Calle 109)",
        "dir": "Calle 109 #17-14, Bogotá, Colombia",
        "maps_query": "La Bifería parrilla Calle 109 Bogotá",
        "lat": 4.6920, "lng": -74.0400,
        "descripcion": "Parrilla de referencia en el norte: cortes generosos, buena papa con pellejo y ensalada de la casa. Costo-beneficio muy bueno para carne de calidad. Popular con familias bogotanas los fines de semana.",
        "confianza": "media",
    },
    {
        "city_display": "Bogotá", "name": "Galería Café Libro",
        "category": "restaurante", "zona": "Norte (Usaquén / Calle 62)",
        "dir": "Avenida 19 #118-30, Bogotá, Colombia",
        "maps_query": "Galería Café Libro Bogotá",
        "lat": 4.6970, "lng": -74.0445,
        "descripcion": "Institución bogotana de más de 39 años: bar cultural con galería de arte, chimenea en terraza y música en vivo de salsa y jazz. Ambiente bohemio, bueno para cócteles y conversación larga.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Donostiarra",
        "category": "restaurante", "zona": "Zona G / Chapinero",
        "dir": "Carrera 5 #67-23, Bogotá, Colombia",
        "maps_query": "Donostiarra Bar Restaurante Bogotá Chapinero",
        "lat": 4.6505, "lng": -74.0595,
        "descripcion": "Cocina vasca en Bogotá: pintxos, pulpo, merluza y la mejor tortilla española de la ciudad. Ambiente cálido de bar español, con vinos de la Rioja. Clásico confiable para cuando se antoja algo ibérico.",
        "confianza": "alta",
    },

    # ── Bares / vida nocturna adicionales ──
    {
        "city_display": "Bogotá", "name": "Video Club",
        "category": "bar", "zona": "Chapinero",
        "dir": "Calle 64 #13-09, Bogotá, Colombia",
        "maps_query": "Video Club discoteca electrónica Bogotá",
        "lat": 4.6488, "lng": -74.0622,
        "descripcion": "Club de música electrónica referente de Bogotá: techno, house y sets de DJs internacionales en tres ambientes — dos pistas y terraza. La escena electrónica más seria de la ciudad. Jue–Sáb desde las 10pm.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Quiebracanto",
        "category": "bar", "zona": "La Candelaria / Centro",
        "dir": "Carrera 5 #17-76, Bogotá, Colombia",
        "maps_query": "Quiebracanto bar salsa Bogotá",
        "lat": 4.6005, "lng": -74.0722,
        "descripcion": "Bar de salsa clásica con más de 40 años de historia, fundado por estudiantes de la Nacional. Orquestas en vivo los viernes; la salsa más auténtica de Bogotá. Mié–Jue 6pm–3am, Vie–Sáb 4pm–3am.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Son Havana",
        "category": "bar", "zona": "Chapinero",
        "dir": "Calle 64 #13-52, Bogotá, Colombia",
        "maps_query": "Son Havana bar salsa cubana Bogotá",
        "lat": 4.6490, "lng": -74.0618,
        "descripcion": "Salsa clásica y música cubana de vieja guardia. Clases de baile miércoles, jueves y sábados de 7–9pm. Ambiente intimista y auténtico, favorito de la comunidad universitaria. Jue–Sáb hasta las 5am.",
        "confianza": "alta",
    },

    # ── Cultura / atracciones adicionales ──
    {
        "city_display": "Bogotá", "name": "Teatro Colón",
        "category": "atraccion", "zona": "La Candelaria",
        "dir": "Calle 10 #5-32, Bogotá, Colombia",
        "maps_query": "Teatro Colón Bogotá",
        "lat": 4.5968, "lng": -74.0740,
        "descripcion": "El teatro nacional de Colombia (1892), Patrimonio Cultural de la Nación. Arquitectura neoclásica italiana, sala de 773 butacas con acústica excepcional. Visitas guiadas diarias 10am–4pm (en español, inglés y portugués). Consultar programación de ópera, ballet y conciertos.",
        "confianza": "muy_alta",
    },
    {
        "city_display": "Bogotá", "name": "Biblioteca Luis Ángel Arango",
        "category": "atraccion", "zona": "La Candelaria",
        "dir": "Calle 11 #4-14, Bogotá, Colombia",
        "maps_query": "Biblioteca Luis Ángel Arango Bogotá",
        "lat": 4.5972, "lng": -74.0735,
        "descripcion": "Una de las bibliotecas más visitadas del mundo: colección de arte, conciertos de cámara gratuitos, exposiciones y la mejor sala de lectura del centro histórico. Entrada libre. A pasos del Museo del Oro y el Teatro Colón.",
        "confianza": "muy_alta",
    },
    {
        "city_display": "Bogotá", "name": "Cinemateca de Bogotá",
        "category": "atraccion", "zona": "Centro Internacional",
        "dir": "Carrera 7 #22-79, Bogotá, Colombia",
        "maps_query": "Cinemateca de Bogotá",
        "lat": 4.6120, "lng": -74.0695,
        "descripcion": "Centro de cine de arte y patrimonio fílmico colombiano. Ciclos temáticos, retrospectivas y filmes de autor que no llegan a salas comerciales. Entrada económica o gratuita. Buen plan cultural en el centro.",
        "confianza": "media",
    },
    {
        "city_display": "Bogotá", "name": "Museo de Arte Moderno de Bogotá (MAMBO)",
        "category": "atraccion", "zona": "Teusaquillo / Centro",
        "dir": "Calle 24 #6-00, Bogotá, Colombia",
        "maps_query": "Museo de Arte Moderno Bogotá MAMBO",
        "lat": 4.6138, "lng": -74.0712,
        "descripcion": "Museo con la mejor colección de arte colombiano del siglo XX: Alejandro Obregón, Fernando Botero, Edgar Negret. Exposiciones temporales de artistas contemporáneos latinoamericanos. Junto al Planetario.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Graffiti Tour La Candelaria",
        "category": "experiencia", "zona": "La Candelaria",
        "dir": "Plaza del Chorro de Quevedo, Bogotá, Colombia",
        "maps_query": "Bogotá Graffiti Tour La Candelaria",
        "lat": 4.5985, "lng": -74.0748,
        "descripcion": "Tour gratuito (propina sugerida) por el arte urbano de La Candelaria, reconocido entre los mejores del mundo. Guías que explican contexto político y artístico. Sale de la Plaza del Chorro de Quevedo. Reservar en bogotaGraffitiTour.com.",
        "confianza": "muy_alta",
    },
    {
        "city_display": "Bogotá", "name": "Media Torta",
        "category": "atraccion", "zona": "La Candelaria / Cerros",
        "dir": "Calle 7B #2-80, Bogotá, Colombia",
        "maps_query": "Media Torta Bogotá anfiteatro",
        "lat": 4.5935, "lng": -74.0698,
        "descripcion": "Anfiteatro al aire libre al pie de los cerros orientales con capacidad para 5.000 personas. Conciertos gratuitos de música colombiana, jazz y eventos culturales. Consultar cartelera en cultura.gov.co.",
        "confianza": "media",
    },

    # ── Clínica adicional (Chapinero) ──
    {
        "city_display": "Bogotá", "name": "Clínica de Marly",
        "category": "clinica", "zona": "Chapinero",
        "dir": "Calle 50 #9-67, Bogotá, Colombia",
        "maps_query": "Clínica de Marly urgencias Bogotá",
        "lat": 4.6358, "lng": -74.0640,
        "descripcion": "Clínica de 120 años de historia, entre las 10 mejores de Colombia. Urgencias 24h. Tel.: +57 601 343-6600 · +57 315 177-5500. Ubicada en Chapinero, accesible para viajeros en esa zona. Emergencias Colombia: 123.",
        "confianza": "muy_alta",
    },

    # ── Infraestructura financiera ──
    {
        "city_display": "Bogotá", "name": "Cajeros Bancolombia (Zona T)",
        "category": "transporte", "zona": "Zona T / El Retiro",
        "dir": "Carrera 13 #85-60, Bogotá, Colombia",
        "maps_query": "Bancolombia cajero Zona T Bogotá",
        "lat": 4.6678, "lng": -74.0530,
        "descripcion": "Cajeros Bancolombia en la Zona T (el banco más grande de Colombia). Para retirar pesos colombianos (COP) con tarjeta internacional. Comisión extranjera habitual: ~$8.000–15.000 COP. También hay cajeros Davivienda y BBVA en el Centro Comercial El Retiro.",
        "confianza": "media",
    },

    # ════════════ EXPANSIÓN 3: cadenas ícono + sedes ancla ════════════
    # Para CUALQUIER otra sede de cadena, el Companion usa búsqueda en vivo
    # (endpoint /nearby-chain con Google Places). Estas son solo anclas/íconos.

    # ── Íconos colombianos de cadena (que un turista querría conocer) ──
    {
        "city_display": "Bogotá", "name": "Crepes & Waffles (Parque 93)",
        "category": "restaurante", "zona": "Parque de la 93",
        "dir": "Calle 93 #12-10, Bogotá, Colombia",
        "maps_query": "Crepes & Waffles Parque 93 Bogotá",
        "lat": 4.6765, "lng": -74.0485,
        "descripcion": "Cadena colombiana icónica (desde 1980), famosa por sus crepes dulces y salados, heladería y por emplear a madres cabeza de hogar. Calidad consistente a buen precio. Un clásico que vale la pena probar. Esta sede está junto al Parque de la 93.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Crepes & Waffles (Zona T / Calle 85)",
        "category": "restaurante", "zona": "Zona T",
        "dir": "Carrera 11 #85-75, Bogotá, Colombia",
        "maps_query": "Crepes & Waffles Calle 85 Bogotá",
        "lat": 4.6685, "lng": -74.0540,
        "descripcion": "Sede de la cadena colombiana ícono en plena Zona T. Crepes, ensaladas, postres y los famosos helados artesanales. Ideal para una comida casual de calidad mientras recorres la zona rosa.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "Juan Valdez Café (Zona G)",
        "category": "cafe", "zona": "Zona G / Chapinero",
        "dir": "Carrera 6 #66-46, Bogotá, Colombia",
        "maps_query": "Juan Valdez Café Zona G Bogotá",
        "lat": 4.6575, "lng": -74.0588,
        "descripcion": "La cadena de café insignia de Colombia, de la Federación de Cafeteros. Café 100% colombiano de origen, ambiente cómodo y wifi. El símbolo cafetero del país — buen lugar para probar un tinto campesino o un cortado. Muchas sedes en la ciudad.",
        "confianza": "alta",
    },
    {
        "city_display": "Bogotá", "name": "El Corral (Zona T)",
        "category": "restaurante", "zona": "Zona T",
        "dir": "Carrera 13 #82-50, Bogotá, Colombia",
        "maps_query": "Hamburguesas El Corral Zona T Bogotá",
        "lat": 4.6672, "lng": -74.0535,
        "descripcion": "La hamburguesería colombiana por excelencia (desde 1983). Las hamburguesas a la parrilla más queridas del país, un peldaño por encima del fast food internacional. Opción rápida y confiable. Muchas sedes; esta está en la Zona T.",
        "confianza": "media",
    },

    # ── Sedes ancla de supermercados (zonas turísticas) ──
    {
        "city_display": "Bogotá", "name": "Carulla Calle 63 (Chapinero)",
        "category": "supermercado", "zona": "Chapinero",
        "dir": "Calle 63 con Carrera 7, Bogotá, Colombia",
        "maps_query": "Carulla Calle 63 Chapinero Bogotá",
        "lat": 4.6490, "lng": -74.0625,
        "descripcion": "Supermercado premium en Chapinero, cerca de la Basílica de Lourdes y la estación Calle 63. Surtido completo, panadería y restaurante interno. Lun–Sáb 6am–11pm aprox.",
        "confianza": "media",
    },
    {
        "city_display": "Bogotá", "name": "Éxito Norte (Calle 134)",
        "category": "supermercado", "zona": "Norte (Cedritos)",
        "dir": "Calle 134 con Autopista Norte, Bogotá, Colombia",
        "maps_query": "Éxito Calle 134 Autopista Norte Bogotá",
        "lat": 4.7180, "lng": -74.0480,
        "descripcion": "Hipermercado Éxito grande en el norte (Cedritos/Autopista). Mercado, electrónica, ropa y comida. El más completo de la zona norte. Lun–Dom 8am–10pm.",
        "confianza": "media",
    },
    {
        "city_display": "Bogotá", "name": "Carulla Usaquén (Calle 116)",
        "category": "supermercado", "zona": "Usaquén",
        "dir": "Carrera 15 #116-50, Bogotá, Colombia",
        "maps_query": "Carulla Usaquén Calle 116 Bogotá",
        "lat": 4.6960, "lng": -74.0320,
        "descripcion": "Carulla premium en Usaquén, cerca de la zona del mercado de pulgas y los restaurantes. Surtido completo y panadería. Útil para viajeros alojados en el norte.",
        "confianza": "media",
    },

    # ── Sedes ancla de centros comerciales que faltaban ──
    {
        "city_display": "Bogotá", "name": "Centro Comercial Atlantis Plaza",
        "category": "compras", "zona": "Zona T / Parque 93",
        "dir": "Calle 81 #11-94, Bogotá, Colombia",
        "maps_query": "Centro Comercial Atlantis Plaza Bogotá",
        "lat": 4.6660, "lng": -74.0535,
        "descripcion": "Centro comercial en plena Zona Rosa con cine, tiendas, restaurantes y vida nocturna. Punto de referencia y encuentro entre la Zona T y el Parque 93. Cajeros y comida disponibles.",
        "confianza": "media",
    },
    {
        "city_display": "Bogotá", "name": "Centro Comercial Andino",
        "category": "compras", "zona": "Zona T / El Retiro",
        "dir": "Carrera 11 #82-71, Bogotá, Colombia",
        "maps_query": "Centro Comercial Andino Bogotá",
        "lat": 4.6668, "lng": -74.0540,
        "descripcion": "El centro comercial más emblemático de la Zona Rosa: marcas internacionales de lujo, restaurantes, cine y cajeros. Punto de referencia central de la zona T y refugio cuando llueve. (Si ya está curado, ignóralo.)",
        "confianza": "media",
    },
    {
        "city_display": "Bogotá", "name": "Centro Comercial Titán Plaza",
        "category": "compras", "zona": "Noroccidente (Av. Boyacá)",
        "dir": "Avenida Boyacá #80-94, Bogotá, Colombia",
        "maps_query": "Centro Comercial Titán Plaza Bogotá",
        "lat": 4.6880, "lng": -74.0980,
        "descripcion": "Gran centro comercial en el noroccidente, con cine, tiendas, supermercado y patio de comidas. Útil si te alojas o mueves por esa zona.",
        "confianza": "baja",
    },

]

# Fallback para entradas futuras sin lat/lng propios cuya zona tampoco esté en
# geo.ZONE_COORDS.
_ZIPAQUIRA = (5.0190, -73.9905)


def all_seeds() -> list[dict]:
    """Resuelve lat/lng de cada lugar.

    Prioridad: 1) lat/lng propios. 2) si faltan, fallback al punto de la zona
    (geo.zone_coords) o a _ZIPAQUIRA. El campo `dir` (dirección) y `maps_query`
    se conservan en el dict; db.seed_destination_places ignora las claves que no
    sean columnas, así que no estorban.
    """
    out = []
    for p in BOGOTA:
        if "lat" in p and "lng" in p:
            lat, lng = p["lat"], p["lng"]
        elif "afuera" in p["zona"].lower() or "boyac" in p["zona"].lower():
            lat, lng = _ZIPAQUIRA
        else:
            coords = geo.zone_coords(p["city_display"], p["zona"])
            lat, lng = coords if coords else (0.0, 0.0)
        out.append({**p, "lat": lat, "lng": lng})
    return out
